package com.baz.sekill.mapper;

import com.baz.sekill.model.SkBill;

public interface SkBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_bill
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_bill
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    int insert(SkBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_bill
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    int insertSelective(SkBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_bill
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    SkBill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_bill
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    int updateByPrimaryKeySelective(SkBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_bill
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    int updateByPrimaryKey(SkBill record);
}