package com.baz.sekill.mapper;

import com.baz.sekill.model.SkUser;
import org.apache.ibatis.annotations.Param;

public interface SkUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_user
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_user
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    int insert(SkUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_user
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    int insertSelective(SkUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_user
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    SkUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_user
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    int updateByPrimaryKeySelective(SkUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_user
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    int updateByPrimaryKey(SkUser record);

    /**
     * 根据用户名密码查询
     * @param username
     * @param password
     * @return
     */
    SkUser selectByUsernameAndPwd(@Param("username")String username,@Param("password")String password);
}