package com.baz.sekill.model;

import java.util.Date;

public class SkKill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sk_kill.id
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sk_kill.goods_name
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    private String goods_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sk_kill.goods_pic
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    private String goods_pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sk_kill.good_discreble
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    private String good_discreble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sk_kill.goods_count
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    private Long goods_count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sk_kill.start_time
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    private Date start_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sk_kill.end_time
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    private Date end_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sk_kill.creat_time
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    private Date creat_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sk_kill.update_time
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    private Date update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sk_kill.id
     *
     * @return the value of sk_kill.id
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sk_kill.id
     *
     * @param id the value for sk_kill.id
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sk_kill.goods_name
     *
     * @return the value of sk_kill.goods_name
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public String getGoods_name() {
        return goods_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sk_kill.goods_name
     *
     * @param goods_name the value for sk_kill.goods_name
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public void setGoods_name(String goods_name) {
        this.goods_name = goods_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sk_kill.goods_pic
     *
     * @return the value of sk_kill.goods_pic
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public String getGoods_pic() {
        return goods_pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sk_kill.goods_pic
     *
     * @param goods_pic the value for sk_kill.goods_pic
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public void setGoods_pic(String goods_pic) {
        this.goods_pic = goods_pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sk_kill.good_discreble
     *
     * @return the value of sk_kill.good_discreble
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public String getGood_discreble() {
        return good_discreble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sk_kill.good_discreble
     *
     * @param good_discreble the value for sk_kill.good_discreble
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public void setGood_discreble(String good_discreble) {
        this.good_discreble = good_discreble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sk_kill.goods_count
     *
     * @return the value of sk_kill.goods_count
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public Long getGoods_count() {
        return goods_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sk_kill.goods_count
     *
     * @param goods_count the value for sk_kill.goods_count
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public void setGoods_count(Long goods_count) {
        this.goods_count = goods_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sk_kill.start_time
     *
     * @return the value of sk_kill.start_time
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public Date getStart_time() {
        return start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sk_kill.start_time
     *
     * @param start_time the value for sk_kill.start_time
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public void setStart_time(Date start_time) {
        this.start_time = start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sk_kill.end_time
     *
     * @return the value of sk_kill.end_time
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public Date getEnd_time() {
        return end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sk_kill.end_time
     *
     * @param end_time the value for sk_kill.end_time
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public void setEnd_time(Date end_time) {
        this.end_time = end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sk_kill.creat_time
     *
     * @return the value of sk_kill.creat_time
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public Date getCreat_time() {
        return creat_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sk_kill.creat_time
     *
     * @param creat_time the value for sk_kill.creat_time
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public void setCreat_time(Date creat_time) {
        this.creat_time = creat_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sk_kill.update_time
     *
     * @return the value of sk_kill.update_time
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sk_kill.update_time
     *
     * @param update_time the value for sk_kill.update_time
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }
}