package com.baz.sekill.model;

import java.util.Date;

public class SkUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sk_user.id
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sk_user.username
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sk_user.password
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sk_user.phone
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sk_user.creat_time
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    private Date creat_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sk_user.update_time
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sk_user.last_login
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    private Date last_login;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sk_user.id
     *
     * @return the value of sk_user.id
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sk_user.id
     *
     * @param id the value for sk_user.id
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sk_user.username
     *
     * @return the value of sk_user.username
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sk_user.username
     *
     * @param username the value for sk_user.username
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sk_user.password
     *
     * @return the value of sk_user.password
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sk_user.password
     *
     * @param password the value for sk_user.password
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sk_user.phone
     *
     * @return the value of sk_user.phone
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sk_user.phone
     *
     * @param phone the value for sk_user.phone
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sk_user.creat_time
     *
     * @return the value of sk_user.creat_time
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public Date getCreat_time() {
        return creat_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sk_user.creat_time
     *
     * @param creat_time the value for sk_user.creat_time
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public void setCreat_time(Date creat_time) {
        this.creat_time = creat_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sk_user.update_time
     *
     * @return the value of sk_user.update_time
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sk_user.update_time
     *
     * @param update_time the value for sk_user.update_time
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sk_user.last_login
     *
     * @return the value of sk_user.last_login
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public Date getLast_login() {
        return last_login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sk_user.last_login
     *
     * @param last_login the value for sk_user.last_login
     *
     * @mbggenerated Mon Apr 15 10:02:17 CST 2019
     */
    public void setLast_login(Date last_login) {
        this.last_login = last_login;
    }
}